### ISSUE TITLE
Add validation

### ISSUE THREAD

**Issue by tareiking** [tareiking/Custom-Meta-Boxes#2]
Let's add some validation to CMB.

**Roadmap (estimated:  End of November, 2016)**
- [ ] Parsley: Add support for parsley [built-in validators](http://parsleyjs.org/doc/index.html#psly-validators-list).
- [ ] Parsley: Add support for custom messages using data-attributes.
- [ ] Allow developers to override Parsley JS object.
- [ ] PHPUnit Tests.
- [ ] Add visual style.
- [ ] Validate/sanitize validation arguments.
- [ ] Test groups and repeating fields.
